export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const DELETE_AUTH_ERROR = 'DELETE_AUTH_ERROR';
export const DELETE_AUTH_SUCCESS = 'DELETE_AUTH_SUCCESS';
export const ON_USER_ADMIN = 'ON_USER_ADMIN';
export const OFF_USER_ADMIN = 'OFF_USER_ADMIN';
export const SET_AUTO_REDIRECT_PATH = 'SET_AUTO_REDIRECT_PATH';

export const POST_START = 'POST_START';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAIL = 'POST_FAIL';