export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const DELETE_AUTH_ERROR = 'DELETE_AUTH_ERROR';
export const DELETE_AUTH_SUCCESS = 'DELETE_AUTH_SUCCESS';